import type { Project } from "@/types";
import { CATEGORY_META, SEVERITY_META } from "@/types";

/**
 * Export generators for the audit report (PRD §11.7). All three formats are
 * produced client-side so no server round-trip is required.
 */

export type ExportFormat = "pdf" | "markdown" | "json";

function statusCount(project: Project) {
  const f = project.analysis?.findings ?? [];
  return {
    critical: f.filter((x) => x.severity === "critical").length,
    major: f.filter((x) => x.severity === "major").length,
    minor: f.filter((x) => x.severity === "minor").length,
    open: f.filter((x) => x.status === "open").length,
    accepted: f.filter((x) => x.status === "accepted").length,
    ignored: f.filter((x) => x.status === "ignored").length,
    resolved: f.filter((x) => x.status === "resolved").length,
  };
}

export function buildMarkdown(project: Project): string {
  const a = project.analysis;
  const c = statusCount(project);
  const date = new Date().toLocaleString();
  const lines: string[] = [];
  lines.push(`# SpecGuard AI — Audit Report`);
  lines.push("");
  lines.push(`**Project:** ${project.name}`);
  lines.push(`**Version:** ${project.currentVersion}`);
  lines.push(`**Generated:** ${date}`);
  if (project.demoKey) lines.push(`**Source:** Demo project`);
  lines.push("");

  if (a) {
    lines.push(`## Summary`);
    lines.push(a.summary);
    lines.push("");
    lines.push(`## Scores`);
    lines.push(`| Metric | Score |`);
    lines.push(`| --- | --- |`);
    lines.push(`| Completeness | ${a.scores.completeness}% |`);
    lines.push(`| Ambiguity | ${a.scores.ambiguity}% |`);
    lines.push(`| Testability | ${a.scores.testability}% |`);
    lines.push(`| Consistency | ${a.scores.consistency}% |`);
    lines.push("");
    lines.push(`## Issue Breakdown`);
    lines.push(`- **Critical:** ${c.critical}`);
    lines.push(`- **Major:** ${c.major}`);
    lines.push(`- **Minor:** ${c.minor}`);
    lines.push(`- Resolved: ${c.resolved} · Accepted: ${c.accepted} · Ignored: ${c.ignored} · Open: ${c.open}`);
    lines.push("");

    lines.push(`## Findings`);
    a.findings.forEach((f, i) => {
      const cat = CATEGORY_META[f.category].label;
      const sev = SEVERITY_META[f.severity].label;
      lines.push(`### ${i + 1}. ${f.title}`);
      lines.push(`- **Category:** ${cat}`);
      lines.push(`- **Severity:** ${sev}`);
      lines.push(`- **Status:** ${f.status}`);
      if (f.location) lines.push(`- **Location:** ${f.location}`);
      lines.push("");
      lines.push(f.description);
      lines.push("");
      if (f.recommendation) {
        lines.push(`> **Recommendation:** ${f.recommendation}`);
        lines.push("");
      }
    });
  } else {
    lines.push(`_No analysis has been run for this project yet._`);
  }

  lines.push(`---`);
  lines.push(`_Generated by SpecGuard AI._`);
  return lines.join("\n");
}

export function buildJson(project: Project): string {
  return JSON.stringify(
    {
      project: {
        id: project.id,
        name: project.name,
        version: project.currentVersion,
        demo: Boolean(project.demoKey),
        generatedAt: new Date().toISOString(),
      },
      analysis: project.analysis ?? null,
      counts: statusCount(project),
    },
    null,
    2,
  );
}

/** Build a self-contained, printable HTML report and open the print dialog. */
export function exportPdf(project: Project) {
  const md = buildMarkdown(project);
  const html = `<!doctype html><html><head><meta charset="utf-8" />
  <title>SpecGuard AI — ${escapeHtml(project.name)} — Audit Report</title>
  <style>
    :root { color-scheme: light; }
    * { box-sizing: border-box; }
    body { font-family: Inter, -apple-system, system-ui, sans-serif; background:#f5f2ed; color:#1b1b1b; margin:0; padding:40px; }
    .sheet { max-width: 800px; margin: 0 auto; background:#fff; border:3px solid #000; box-shadow: 8px 8px 0 #000; padding: 40px; }
    h1 { font-size: 32px; margin: 0 0 8px; font-weight: 900; letter-spacing:-0.02em; border-bottom: 3px solid #000; padding-bottom: 8px; }
    h2 { font-size: 22px; margin: 28px 0 10px; font-weight: 800; }
    h3 { font-size: 17px; margin: 20px 0 6px; font-weight: 800; }
    table { border-collapse: collapse; width: 100%; margin: 10px 0; }
    th, td { border: 2px solid #000; padding: 8px; text-align: left; font-size: 14px; }
    th { background:#e8e8e8; }
    blockquote { border-left: 4px solid #000; margin: 12px 0; padding: 4px 14px; background:#f3f3f3; }
    code, pre { font-family: ui-monospace, monospace; }
    ul { line-height: 1.6; }
    .meta { color:#4c4546; font-size: 14px; margin-bottom: 20px; }
    @media print { body { background:#fff; padding:0; } .sheet { box-shadow:none; border:0; max-width:none; padding: 0 12mm; } }
  </style></head>
  <body><div class="sheet">${renderMarkdownToHtml(md)}</div>
  <script>window.onload = () => { setTimeout(() => window.print(), 350); };</script>
  </body></html>`;
  openBlob(html, "text/html", true);
}

export function exportMarkdown(project: Project) {
  const md = buildMarkdown(project);
  downloadBlob(
    new Blob([md], { type: "text/markdown;charset=utf-8" }),
    fileName(project, "md"),
  );
}

export function exportJson(project: Project) {
  const json = buildJson(project);
  downloadBlob(
    new Blob([json], { type: "application/json;charset=utf-8" }),
    fileName(project, "json"),
  );
}

export function exportReport(project: Project, format: ExportFormat) {
  if (format === "pdf") return exportPdf(project);
  if (format === "markdown") return exportMarkdown(project);
  return exportJson(project);
}

// ---- helpers ----

function fileName(project: Project, ext: string) {
  const base = project.name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
  return `specguard-${base}-${project.currentVersion}.${ext}`;
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function openBlob(html: string, type: string, _print: boolean) {
  const blob = new Blob([html], { type: `${type};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, "_blank");
  if (!win) {
    // Pop-up blocked — fall back to a same-tab navigation.
    window.location.href = url;
  }
  setTimeout(() => URL.revokeObjectURL(url), 60000);
}

function escapeHtml(s: string) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/** Tiny markdown→HTML renderer sufficient for the report (headings, lists, table, blockquote, bold). */
function renderMarkdownToHtml(md: string): string {
  const esc = escapeHtml;
  const lines = md.split("\n");
  let html = "";
  let inUl = false;
  let inTable = false;
  let tableHeader = false;
  const closeUl = () => { if (inUl) { html += "</ul>"; inUl = false; } };
  const closeTable = () => { if (inTable) { html += "</tbody></table>"; inTable = false; } };

  const inline = (s: string) =>
    esc(s)
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      .replace(/`([^`]+)`/g, "<code>$1</code>");

  for (const raw of lines) {
    const line = raw.replace(/\s+$/, "");
    if (/^### /.test(line)) { closeUl(); closeTable(); html += `<h3>${inline(line.slice(4))}</h3>`; continue; }
    if (/^## /.test(line)) { closeUl(); closeTable(); html += `<h2>${inline(line.slice(3))}</h2>`; continue; }
    if (/^# /.test(line)) { closeUl(); closeTable(); html += `<h1>${inline(line.slice(2))}</h1>`; continue; }
    if (/^---$/.test(line)) { closeUl(); closeTable(); html += "<hr/>"; continue; }
    if (/^\| .+\|$/.test(line)) {
      closeUl();
      const cells = line.split("|").slice(1, -1).map((c) => c.trim());
      if (!inTable) { html += "<table><thead>"; tableHeader = true; inTable = true; }
      if (cells.every((c) => /^-+$/.test(c))) { html += "</thead><tbody>"; tableHeader = false; continue; }
      const tag = tableHeader ? "th" : "td";
      html += `<tr>${cells.map((c) => `<${tag}>${inline(c)}</${tag}>`).join("")}</tr>`;
      continue;
    }
    if (/^- /.test(line)) {
      closeTable();
      if (!inUl) { html += "<ul>"; inUl = true; }
      html += `<li>${inline(line.slice(2))}</li>`;
      continue;
    }
    if (/^> /.test(line)) { closeUl(); closeTable(); html += `<blockquote>${inline(line.slice(2))}</blockquote>`; continue; }
    if (line.trim() === "") { closeUl(); closeTable(); continue; }
    closeUl(); closeTable();
    html += `<p>${inline(line)}</p>`;
  }
  closeUl(); closeTable();
  return html;
}
